# Generated by Django 6.0.7 on 2026-09-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinician',
            name='department_name',
            field=models.CharField(default='Ophthalmology Department', max_length=150),
        ),
        migrations.AddField(
            model_name='clinician',
            name='facility_name',
            field=models.CharField(default='St. Jude Medical Center', max_length=150),
        ),
        migrations.AddField(
            model_name='clinician',
            name='lab_details',
            field=models.CharField(default='Clinical Analysis Lab #4-B', max_length=150),
        ),
    ]
