# Generated by Django 6.0.7 on 2026-07-21 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_image', models.ImageField(upload_to='uploads/')),
                ('disc_mask', models.ImageField(blank=True, null=True, upload_to='masks/')),
                ('cup_mask', models.ImageField(blank=True, null=True, upload_to='masks/')),
                ('overlay_image', models.ImageField(blank=True, null=True, upload_to='overlays/')),
                ('disc_area', models.FloatField(blank=True, null=True)),
                ('cup_area', models.FloatField(blank=True, null=True)),
                ('vcdr', models.FloatField(blank=True, null=True)),
                ('diagnosis', models.CharField(default='Pending', max_length=100)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='analysis.patient')),
            ],
        ),
    ]
