# Generated by Django 6.0.7 on 2026-07-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='cdar',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='cup_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='cup_prob_map',
            field=models.FileField(blank=True, null=True, upload_to='results/prob_maps/'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='cup_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='disc_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='disc_prob_map',
            field=models.FileField(blank=True, null=True, upload_to='results/prob_maps/'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='disc_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='hcdr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='preprocessed_image',
            field=models.ImageField(blank=True, null=True, upload_to='results/preprocessed/'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='rim_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='rim_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='cup_mask',
            field=models.ImageField(blank=True, null=True, upload_to='results/cup/'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='disc_mask',
            field=models.ImageField(blank=True, null=True, upload_to='results/disc/'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='overlay_image',
            field=models.ImageField(blank=True, null=True, upload_to='results/overlay/'),
        ),
    ]
